Cargo.lock, Cargo.toml, README.md, fixtures/without-package-json/package.json, fixtures/without-package-json/packages/def/package.json, src/collect.rs, src/main.rs, src/packages/mod.rs, src/packages/root.rs, src/rules/empty_dependencies.rs, src/rules/mod.rs, src/rules/packages_without_package_json.rs
Detect packages that don't have a `package.json` file in their directory. Warning by default because it might be intended, but is not an ideal pattern: you should instead remove this package from the monorepo packages.
=> feat: add packages without package.json rule

README.md, fixtures/dependencies-star/docs/package.json, fixtures/dependencies-star/package.json, fixtures/dependencies-star/packages/abc/package.json, fixtures/dependencies-star/packages/def/package.json, src/collect.rs, src/rules/empty_dependencies.rs, src/rules/packages_without_package_json.rs, src/rules/root_package_dependencies.rs
- Improve README with more examples 
- `empty-dependencies` is now an error
- Ignore dependencies versions that are `*`, since they match any other defined version in the monorepo
=> refactor: improve README & tweak issues level

README.md, src/collect.rs, src/packages/mod.rs, src/rules/mod.rs, src/rules/types_in_dependencies.rs
Closes https://github.com/QuiiBz/sherif/issues/8
Private packages shouldn't have `@types/*` in `dependencies`, since they don't need it at runtime. Move them to `devDependencies`.
=> feat: add types in dependencies rule

src/rules/multiple_dependency_versions.rs, src/rules/snapshots/sherif__rules__multiple_dependency_versions__test__order_multiple.snap
Regression of https://github.com/QuiiBz/sherif/pull/10
=> fix: multiple-dependency-versions ordering

.github/workflows/ci.yml
Fix https://github.com/QuiiBz/sherif/actions/runs/6717896270/job/18256581231?pr=14 by always using stable Rust in the CI
=> chore(ci): always use stable rust

src/args.rs, src/collect.rs, src/main.rs, src/printer.rs, src/rules/empty_dependencies.rs, src/rules/mod.rs
Closes #6 
Add a new `--fix` option to autofix issues when possible.
=> feat: autofix `empty-dependencies`

src/rules/root_package_private_field.rs
Relates to https://github.com/QuiiBz/sherif/issues/6
=> feat: autofix `root-package-private-field`

src/rules/multiple_dependency_versions.rs, src/rules/snapshots/sherif__rules__multiple_dependency_versions__test__dedupe.snap, src/rules/snapshots/sherif__rules__multiple_dependency_versions__test__order_multiple.snap, src/rules/snapshots/sherif__rules__multiple_dependency_versions__test__order_single.snap
Increase versions padding for the `multiple-dependency-versions` rule to make it more aligned. Example with the tanstack query repo:
| Before | After |
|--------|--------|
| <img width="1235" alt="Screenshot 2023-11-11 at 08 46 30" src="https://github.com/QuiiBz/sherif/assets/43268759/6efdceb7-ab95-4bc7-9f19-515732adafd5"> | <img width="1212" alt="Screenshot 2023-11-11 at 09 01 37" src="https://github.com/QuiiBz/sherif/assets/43268759/8e401ca5-52ae-4250-993f-c5b0b2607a0d"> |
=> fix(multiple-dependency-versions): increase versions padding

README.md, fixtures/basic/package.json, fixtures/pnpm/pnpm-workspace.yaml, src/collect.rs, src/rules/mod.rs, src/rules/non_existant_packages.rs, src/rules/packages_without_package_json.rs, src/rules/snapshots/sherif__rules__non_existant_packages__test__package_workspace.snap, src/rules/snapshots/sherif__rules__non_existant_packages__test__pnpm_workspace.snap, src/rules/snapshots/sherif__rules__non_existant_packages__test__test.snap
Closes https://github.com/QuiiBz/sherif/issues/23
All paths defined in the workspace (the root `package.json`' `workspaces` field or `pnpm-workspace.yaml`) should match at least one package.
=> feat: new `non-existant-packages` rule

src/rules/types_in_dependencies.rs
=> fix(types-in-dependencies): autofix when package doesn't have `devDependencies`

src/rules/multiple_dependency_versions.rs, src/rules/snapshots/sherif__rules__multiple_dependency_versions__test__dedupe.snap, src/rules/snapshots/sherif__rules__multiple_dependency_versions__test__order_multiple.snap, src/rules/snapshots/sherif__rules__multiple_dependency_versions__test__order_single.snap
It looks a lot better like this:
=> fix(multiple-dependency-versions): improve formatting for single packages

src/collect.rs, src/packages/mod.rs, src/packages/root.rs, src/rules/packages_without_package_json.rs, src/rules/root_package_private_field.rs
Relates to https://github.com/QuiiBz/sherif/issues/6
- Also fix this same rule from being caught when a package did not have a `name` field (which is technically possible)
- Also fix `root-package-private-field` autofix writing `"true"` instead of `true`
=> feat: autofix `packages-without-package-json`

src/packages/mod.rs, src/packages/root.rs
The check to show this rule was checking the presence of the `private` field instead of the `packageManager` field of the root package.
=> fix(root-package-manager-field): wrong detection

README.md, src/args.rs, src/collect.rs, src/packages/mod.rs
Closes https://github.com/QuiiBz/sherif/issues/41
- `--ignore-package` now supports specifying a path to a specific package
- `--ignore-package` now supports globs
Examples:
```bash
sherif -p @repo/tools
sherif -p @repo-internal/*
sherif -p ./integrations/react
sherif -p ./integrations/*
```
=> feat: allow paths and globs for `--ignore-package`

Cargo.toml
From 2.2MB to 1.1MB on `aarch64-apple-darwin`:
=> perf: reduce binary size

README.md
Closes https://github.com/QuiiBz/sherif/issues/51
Explanation of the issue here: https://github.com/TanStack/query/pull/6701#issuecomment-1903834659
TL;DR: it's not a bug in Sherif, but some shell might interpret and expand `*` so the command is invalid, unless you wrap the argument in quotes.
=> chore: update ignoring with star example

Cargo.lock, Cargo.toml, src/json.rs, src/main.rs, src/rules/empty_dependencies.rs, src/rules/multiple_dependency_versions.rs, src/rules/non_existant_packages.rs, src/rules/root_package_private_field.rs, src/rules/types_in_dependencies.rs
Closes https://github.com/QuiiBz/sherif/issues/54
Using the [`detect-indent`](https://github.com/stefanpenner/detect-indent-rs) crate and `serde_json`'s [`PrettyFormatter`](https://docs.rs/serde_json/latest/serde_json/ser/struct.PrettyFormatter.html#impl-Formatter-for-PrettyFormatter%3C'a%3E), we can preserve the correct indentation.
=> feat: preserve JSON indentation

src/collect.rs
Closes https://github.com/QuiiBz/sherif/issues/64
We might fail to parse a `package.json` if the fields have incorrect types (e.g. `private` being a string instead of a boolean), but we should print that error instead of ignoring it.
=> feat: print packages collect errors

src/rules/multiple_dependency_versions.rs
Sort the autofix selection of `multiple-dependency-versions` to show the highest version first.
=> feat: sort `multiple-dependency-versions` autofix

src/rules/multiple_dependency_versions.rs
Improve the style of `multiple-dependency-versions` when autofixing with `--fix` to make the dependency name bold, so easier to see:
Before:
After:
=> feat: improve multiple-dependency-versions fix style

src/rules/packages_without_package_json.rs
The output in the README screenshot (assets/cover.png) should also be corrected to reflect these changes.
=> fix: grammatical error in `packages-without-package-json`

.github/workflows/release.yml
MacOS 11 has been deprecated: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
So it runs indefinitely: https://github.com/QuiiBz/sherif/actions/runs/9826255490/job/27127484128#logs
=> fix: macos runner

src/collect.rs, src/packages/root.rs, src/rules/multiple_dependency_versions.rs, src/rules/snapshots/sherif__rules__multiple_dependency_versions__test__root.snap
Closes #81
`multiple-dependency-versions` didn't check the root `package.json` dependencies, so we could still have multiple dependencies versions in the workspace.
=> feat: `multiple-dependency-versions` also checks root package

README.md, src/args.rs, src/collect.rs, src/packages/semversion.rs, src/printer.rs
Closes https://github.com/QuiiBz/sherif/issues/83
This updates the `--ignore-dependency / `-i` option to allow passing `dependency@version` arguments instead of only a dependency name.
=> feat: allow ignoring specific dependency and version for `multiple-dependency-versions`

fixtures/dependencies-nested-star/package.json, fixtures/dependencies-nested-star/packages/docs/package.json, fixtures/dependencies-nested-star/packages/other/abc/package.json, fixtures/dependencies-nested-star/packages/other/def/package.json, src/collect.rs
Closes https://github.com/QuiiBz/sherif/issues/88
Allow expanding packages defined in the workspace using `**`. This will expand by one level of folder and can only be used once.
For example, `packages/**/*` is now supported.
=> feat: expand nested packages

src/collect.rs
Closes https://github.com/QuiiBz/sherif/issues/103
Similar to when we close `collect_packages`, we should exit after we fail to parse a single `package.json` (often due to an incorrect field).
=> fix: exit when parsing `package.json` fails

README.md, action/index.js, action/index.ts
If the action doesn't have the `args` param, and the root package.json contains a script called "sherif", pass the arguments of the sherif script to the action to avoid repeating the same args in the root package.json and the action
=> feat(action): reuse args from package.json

README.md, fixtures/dependencies/docs/package.json, fixtures/dependencies/packages/abc/package.json, src/collect.rs
Support this kind of syntax:
```bash
sherif -i "@next/*"
```
=> feat: support basic glob matching when ignoring deps

action/index.js, action/index.ts
Regex could not handle dependencies with "@", "/" or "*"
=> fix(action): regex for args from package.json

README.md, fixtures/unsync/package.json, fixtures/unsync/packages/abc/package.json, fixtures/unsync/packages/def/package.json, src/collect.rs, src/packages/semversion.rs, src/rules/mod.rs, src/rules/snapshots/sherif__rules__unsync_similar_dependencies__tests__basic.snap, src/rules/unsync_similar_dependencies.rs
Similar dependencies in a given `package.json` should use the same version. For example, if you use both `react` and `react-dom` dependencies in the same `package.json`, this rule will enforce that they use the same version.
=> feat: `unsync-similar-dependencies` rule

src/collect.rs
Closes https://github.com/QuiiBz/sherif/issues/86
Ignore hidden directories for the `packages-without-package-json` rule, e.g. `.npm` or `.react-email`
=> fix: ignore hidden directories for `packages-without-package-json`

README.md, src/rules/unsync_similar_dependencies.rs
Added tRPC packages to the list of detected similar dependencies that require consistent versioning within a package.json file. This ensures that related tRPC packages—such as @trpc/client, @trpc/server, @trpc/next, and @trpc/react-query—always use the same version, preventing potential compatibility issues as recommended in their documentation.
=> feat: add `@trpc/*` to similar dependency list

src/install.rs
Adds support for the new `bun.lock` text format released in Bun 1.2 [https://bun.sh/blog/bun-v1.2#introducing-bun-lock](https://bun.sh/blog/bun-v1.2#introducing-bun-lock)
=> feat: support `bun.lock` for automatic package manager resolution

src/rules/unsync_similar_dependencies.rs
Hi :wave:,
I found that prisma also publishes adapters in sync with the main packages, which I've added in the first commit. Also, lexical packages must be in sync for them to work, so here's a list of them, taken from their docs (https://lexical.dev/docs/api/modules/lexical).
This time I also didn't forget to run cargo fmt.
=> feat: add more prisma and lexical to similar deps

.github/workflows/release.yml
Following https://github.com/QuiiBz/sherif/pull/125, missed the last job that publishes the main package to NPM, so the last job failed (and I had to publish the package manually): https://github.com/QuiiBz/sherif/actions/runs/15763109000/job/44434198657
=> [ci] update ubuntu to 22 again
